Add checks for s6-overlay tarball downloads in Dockerfile

diff --git a/images/dev-toolchain/Dockerfile b/images/dev-toolchain/Dockerfile
--- a/images/dev-toolchain/Dockerfile
+++ b/images/dev-toolchain/Dockerfile
@@ -57,9 +57,12 @@ RUN \
 ## s6-overlay
 
 ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
+RUN [ -f /tmp/s6-overlay-noarch.tar.xz ] || (echo "Failed to download s6-overlay tarball!" && exit 1)
 RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
 ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
+RUN [ -f /tmp/s6-overlay-x86_64.tar.xz ] || (echo "Failed to download s6-overlay tarball!" && exit 1)
 RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
+
 
 COPY services.d /etc/services.d
 
